### ISSUE TITLE
Issues while scaling down the nodes

### ISSUE THREAD

**Issue by anrajme** [StackStorm/stackstorm-k8s#317]
Hi there - 

We had a few issues lately while the underlying K8s nodes scaled down. During this event, the pods are being evicted ( killed and recreated) on another node which is expected. However, stackstorm-ha reported a few issues. Initially, it was with the stateful set where the RabbitMQ node failures causing events stuck in a "Schduled" status forever. I'm trying to get rid of this trouble by shifting the RabbitMQ service to a Managed cloud service provider. 

Now, the recent problem is with st2actionrunner, where the pod get evicted while executing a workflow. The event has been marked as "abandoned" and the workflow execution failed. 

<img width="468" alt="image" src="https://user-images.githubusercontent.com/1909476/174549874-a1d2a331-be60-4940-aff4-3d93a784ddd0.png">

```
# st2 execution get 62b019ba420e073fb8f432c3
id: 62b019ba420e073fb8f432c3
action.ref: jira.update_field_value
context.user: xxxxx
parameters:
  field: customfield_14297
  issue_key: xx-96233
  value: Closing Jira 
status: abandoned
start_timestamp: Mon, 20 Jun 2022 06:54:50 UTC
end_timestamp:
log:
  - status: requested
    timestamp: '2022-06-20T06:54:50.171000Z'
  - status: scheduled
    timestamp: '2022-06-20T06:54:50.348000Z'
  - status: running
    timestamp: '2022-06-20T06:54:50.408000Z'
  - status: abandoned
    timestamp: '2022-06-20T06:54:50.535000Z'
result: None
```

In this case,  though we still had another 4 healthy actionrunners running while the one failed where the workflow was executed. 

Wondering whether this is expected behaviour and is acceptable for stackstorm-ha architecture ?

cheers!
