### ISSUE TITLE
EKS and ingress with aws-load-balancer controller

### ISSUE THREAD

**Issue by guzzijones** [StackStorm/stackstorm-k8s#360]
Dropping my ingress settings here for anyone else using EKS with aws-load-balancer controller.  The aws load balancer does not support url rewrite so I am forced to use `/` as the only path for ingress.  I will update this ticket as I tune my settings more for ssl and verify i even need the st2web config setting.

Helm overriding values.yaml settings

# Ingress

```
  ingress:
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/target-type: instance
      # kubernetes.io/tls-acme: "true"
    # Map hosts to paths
    hosts:
      - host: stackstorm-ha.[redacted].com
         # Map paths to services
        paths:
          - path: /
            serviceName: stackstorm-ha-st2web
            servicePort: 80

    # Secure the Ingress by specifying a secret that contains a TLS private key and certificate
    tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.test
    ingressClassName: alb
```
# st2web config

```
  st2web:
  (...)
    config: |
            'use strict';

            /* global angular */
            angular.module('main')
              .constant('st2Config', {

                hosts: [
                  {
                    name: 'stackstorm-ha.[redacted].com',
                    url: 'http://stackstorm-ha.[redacted].com/api',
                    auth: 'http://stackstorm-ha.[redacted].com/auth',
                    stream: 'http://stackstorm-ha.[redacted].com/stream',
                  }
                ]

              });

```
