### ISSUE TITLE
Unable to run st2client , st2web, st2actionrunner as stanley user after adding securityContext

### ISSUE THREAD

**Issue by speaktoabu** [StackStorm/stackstorm-k8s#406]
- Added the following security context for st2client & st2actionrunner.. Getting the following error 
```
securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
```

*Error*

 **st2actionrunner**
```
 unable to open log file: open /root/.sdm/sdm.log: permission denied                                                                                                 │
│ unable to open log file: open /root/.sdm/sdm.log: permission denied       
```                                                                                          │

**st2web**:
`│ /bin/bash: /etc/nginx/conf.d/st2.conf: Permission denied`
**st2client:**
```
stream logs failed container "generate-st2client-config" in pod "stackstorm-st2client-xxx" is waiting to start: CreateContainerConfigError for stackstorm/stackstorm-st2client-xxx (generate-st2client-config)
```
